name: Build & Publish Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_PAT }}

      - name: Build and push the Docker image
        run: |
          docker build . --tag ghcr.io/moncefme/basseer-teaboy-frontend:latest \
          docker push ghcr.io/moncefme/basseer-teaboy-frontend:latest
